### ISSUE TITLE
Add CIS Microsoft 365 Foundations to v1.5.0 (08-31-2022)

### ISSUE THREAD

**Issue by gearbread** [turbot/steampipe-mod-microsoft365-compliance#30]

**Comment by cbruno10** [comment]
Hey @gearbread , thanks for opening this issue!

We haven't had a chance to review v1.5.0 yet, do you know what the changes are from v1.4.0? From our experience, bumping minor versions for CIS reports often contains non-breaking changes, with some new sections, benchmarks, etc.

**Comment by gearbread** [comment]
Not off the top of my head, did some checking to see if there was a detailed change log they keep but couldn't find any. Did find this [blog post ](https://www.cisecurity.org/insights/blog/cis-benchmarks-october-2022-update) with a high level description:

-     Moved, added, and renamed several sections due to changes in the Microsoft 365 Commercial Cloud
-     Where applicable, PowerShell remediation is now using V2 cmdlets over V1
-     Updated 30 recommendations
-     Moved two recommendations
-     Removed two deprecated recommendations (Skype for Business)

**Comment by cbruno10** [comment]
Thanks @gearbread for the info. This isn't currently on our radar, but if anyone is interested in trying to add v1.5.0 as a new benchmark, please let us know if you need any help. The existing benchmark can be used as an example for organization, queries, docs, etc.

**Comment by cbruno10** [comment]
@rajlearner17 Even though v2.0.0 is out, we could add this version, v1.5.0, and v2.0.0, as different users and organizations may be using different versions
