### ISSUE TITLE
Links to queries are broken. 

### ISSUE THREAD

**Issue by hannewijkBDO** [turbot/steampipe-mod-microsoft365-compliance#48]
Links to queries are broken. For example the following URL returns a 404 error: https://hub.steampipe.io/mods/turbot/microsoft365_compliance/queries/azuread_third_party_application_not_allowed. 
However this URL is linked to on https://hub.steampipe.io/mods/turbot/microsoft365_compliance/controls/control.cis_v200_2_2?context=benchmark.cis_v200/benchmark.cis_v200_2#sql

**Comment by misraved** [comment]
Welcome to Steampipe @hannewijkBDO and thanks for spotting the issue 👍.

We will look to get a fix out early 👍.

**Comment by misraved** [comment]
This issue has been fixed in https://github.com/turbot/steampipe-mod-microsoft365-compliance/pull/49
