### ISSUE TITLE
[ Wait    ] Loading Workspace Error: failed to load workspace: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by OleksiyHimranov** [turbot/steampipe-mod-microsoft365-compliance#62]
[ Wait    ] Loading Workspace
Error: failed to load workspace: runtime error: invalid memory address or nil pointer dereference

**Steampipe version (`steampipe -v`)**
v0.18.6

**Plugin version (`steampipe plugin list`)**
+-----------------------------------------------------+---------+--------------+
| Installed Plugin                                    | Version | Connections  |
+-----------------------------------------------------+---------+--------------+
| hub.steampipe.io/plugins/turbot/aws@latest          | 0.123.0 | aws          |
| hub.steampipe.io/plugins/turbot/azure@latest        | 0.51.0  | azure        |
| hub.steampipe.io/plugins/turbot/azuread@latest      | 0.14.0  | azuread      |
| hub.steampipe.io/plugins/turbot/microsoft365@latest | 0.4.1   | microsoft365 |
| hub.steampipe.io/plugins/turbot/openai@latest       | local   |              |
| hub.steampipe.io/plugins/turbot/steampipe@latest    | 0.9.1   | steampipe    |
+-----------------------------------------------------+---------+--------------

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).
Just runned command
`steampipe dashboard`

**Comment by khushboo9024** [comment]
Hi [OleksiyHimranov](https://github.com/OleksiyHimranov)  could you please let us know if the issue mentioned above has been resolved or if it is still persisting?

Thanks

**Comment by OleksiyHimranov** [comment]
Thnaks
After upgrading plugins, it works
