### ISSUE TITLE
Couldn't check "Ensure 'External sharing' of calendars is not available"

### ISSUE THREAD

**Issue by antonin78** [turbot/steampipe-mod-microsoft365-compliance#70]
**Describe the bug**
In CLI and GUI, i couldn't get the output for the test called "Ensure 'External sharing' of calendars is not available".
In CLI, it's stuck at "Running 1 control. (0 complete, 1 running, 0 pending, 0 errors)", and in GUI, the check doesn't end.

**Powerpipe version (`powerpipe -v`)**
v0.4.3

**Steampipe version (`steampipe -v`)**
v0.24.2

**To reproduce**
Just make the check on CIS 3.0.0, or execute the following command in CLI:
`powerpipe control run microsoft365_compliance.control.cis_v200_2_3_3`

**Expected behavior**
I would like the excepted output of this check

**Comment by khushboo9024** [comment]
Hi @antonin78, I apologize for the inconvenience you're experiencing. 

We are looking into this issue on our end. In the meantime, could you please check if you are able to run the following command: `select * from microsoft365_my_calendar`

Thanks.

**Comment by misraved** [comment]
Hello @antonin78 ,

We haven’t received a response in a while, so we’re going to close this issue for now. If this is still a concern or if you have additional details to share, please don’t hesitate to reopen the issue, and we’ll be happy to assist you further.

Thank you for your understanding, and we appreciate your contributions!
